name: Build and Deploy

permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: lock and version
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0

      - name: Install dependencies and build
        run: |
          npm i -g pnpm
          pnpm install 
          pnpm run build
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          folder: build
          ACCESS_TOKEN: ${{ secrets.GITHUBTOKEN }}
